<a href="https://colab.research.google.com/github/24cseaiml156jyotiranjanmohakud/DMPM-LAB-REPO/blob/main/DMPM_LAB_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NORMALIZATION**

In [ ]:
import numpy as np

In [ ]:
#min-max
data = np.array([10, 20, 30, 40, 50])
new_min = 0
new_max = 1
data_min = np.min(data)
data_max = np.max(data)
scaled_data = new_min + ((data - data_min) * (new_max - new_min)) / (data_max - data_min)

print("Original Data:", data)
print("Scaled Data:  ", scaled_data)


Original Data: [10 20 30 40 50]
Scaled Data:   [0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([10,20,30,40,50])
min_val=np.min(a)
max_val=np.max(a)
min_max = (a - min_val) / (max_val - min_val)
print(min_max)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
mean=np.mean(a)
std=np.std(a)
z_score=(a-mean)/std
print(z_score)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
dec_scale=a/10**np.ceil(np.log10(np.max(np.abs(a))))
print(dec_scale)

[0.1 0.2 0.3 0.4 0.5]


In [ ]:
x = np.array([1, 2, 3, 5, 7, 8, 10, 11, 13, 15])
y = np.array([2, 4, 7, 8, 10, 15, 20, 21, 23, 30])

r_matrix = np.corrcoef(x, y)
r_value = r_matrix[0, 1]
print("Correlation Coefficient:", r_value)


Correlation Coefficient: 0.9866190374718473


In [ ]:
data = np.array([
    [50, 65, 80, 95]
])

covariance_matrix = np.cov(data)
print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
375.0


In [ ]:
import numpy as np
from scipy import stats

observed = np.array([
    [22, 18, 10],
    [15, 25, 12]
])

print("--- Observed Frequencies ---")
print(observed)
chi2_stat, p_value, df, expected = stats.chi2_contingency(observed)

print("\n--- Expected Frequencies ---")
print(np.round(expected, 2))

print("\n--- Test Results ---")
print(f"Chi-Square Statistic : {chi2_stat:.4f}")
print(f"Degrees of Freedom   : {df}")
print(f"p-value              : {p_value:.4f}")

--- Observed Frequencies ---
[[22 18 10]
 [15 25 12]]

--- Expected Frequencies ---
[[18.14 21.08 10.78]
 [18.86 21.92 11.22]]

--- Test Results ---
Chi-Square Statistic : 2.6075
Degrees of Freedom   : 2
p-value              : 0.2715
